@path = /api/auth

// Login
POST http://{{domain}}/{{path}}/login
Content-Type: application/json

{
    "username": "vvintorez",
    "password": "Password123!"
}

###

// Register
POST http://{{domain}}/{{path}}/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"
Content-Type: text/plain

vvintorez

--boundary
Content-Disposition: form-data; name="title"
Content-Type: text/plain

Mr

--boundary
Content-Disposition: form-data; name="firstName"
Content-Type: text/plain

Victor

--boundary
Content-Disposition: form-data; name="lastName"
Content-Type: text/plain

Vintorez

--boundary
Content-Disposition: form-data; name="gender"
Content-Type: text/plain

Male

--boundary
Content-Disposition: form-data; name="address1"
Content-Type: text/plain

1 Tordoff Way

--boundary
Content-Disposition: form-data; name="address2"
Content-Type: text/plain

Barry

--boundary
Content-Disposition: form-data; name="address3"
Content-Type: text/plain

Vale of Glamorgan

--boundary
Content-Disposition: form-data; name="postcode"
Content-Type: text/plain

CF62 8ET

--boundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Professional Furniture Seller

--boundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

victorvintorez@proton.me

--boundary
Content-Disposition: form-data; name="telephone"
Content-Type: text/plain

+447985285308

--boundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

Password123!

--boundary
Content-Disposition: form-data; name="profileImage"; filename="profile.jpg"
Content-Type: image/png

< ./test_vars/profileimage.png

--boundary--

###

// Logout
GET http://{{domain}}/{{path}}/logout
