@path = /api/furniture

// Get all furniture
GET http://{{domain}}/{{path}}/

###

// Create Furniture
POST http://{{domain}}/{{path}}/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="furnitureMake"

IKEA

--boundary
Content-Disposition: form-data; name="furnitureModel"

Billy

--boundary
Content-Disposition: form-data; name="furnitureColor"

White

--boundary
Content-Disposition: form-data; name="furnitureType"

Bookcase

--boundary
Content-Disposition: form-data; name="location"

Cardiff

--boundary
Content-Disposition: form-data; name="year"

2019

--boundary
Content-Disposition: form-data; name="video"; filename="furniture_video.webm"
Content-Type: video/webm

< ./test_vars/furniture_video.webm

--boundary
Content-Disposition: form-data; name="images"; filename="billy_bookcase_1.png"
Content-Type: image/png

< ./test_vars/furniture_images/billy_bookcase_1.png

--boundary
Content-Disposition: form-data; name="images"; filename="billy_bookcase_2.png"
Content-Type: image/png

< ./test_vars/furniture_images/billy_bookcase_2.png

--boundary
Content-Disposition: form-data; name="images"; filename="billy_bookcase_3.png"
Content-Type: image/png

< ./test_vars/furniture_images/billy_bookcase_3.png

--boundary
Content-Disposition: form-data; name="images"; filename="billy_bookcase_4.png"
Content-Type: image/png

< ./test_vars/furniture_images/billy_bookcase_4.png

--boundary
Content-Disposition: form-data; name="images"; filename="billy_bookcase_5.png"
Content-Type: image/png

< ./test_vars/furniture_images/billy_bookcase_5.png

--boundary--

###

// Get furniture by ID
GET http://{{domain}}/{{path}}/1

###
