/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const UserLazyImport = createFileRoute("/user")();
const AuthLazyImport = createFileRoute("/auth")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const UserLazyRoute = UserLazyImport.update({
	id: "/user",
	path: "/user",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/user.lazy").then((d) => d.Route));

const AuthLazyRoute = AuthLazyImport.update({
	id: "/auth",
	path: "/auth",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/auth.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/auth": {
			id: "/auth";
			path: "/auth";
			fullPath: "/auth";
			preLoaderRoute: typeof AuthLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/user": {
			id: "/user";
			path: "/user";
			fullPath: "/user";
			preLoaderRoute: typeof UserLazyImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexLazyRoute;
	"/auth": typeof AuthLazyRoute;
	"/user": typeof UserLazyRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexLazyRoute;
	"/auth": typeof AuthLazyRoute;
	"/user": typeof UserLazyRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexLazyRoute;
	"/auth": typeof AuthLazyRoute;
	"/user": typeof UserLazyRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/auth" | "/user";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/auth" | "/user";
	id: "__root__" | "/" | "/auth" | "/user";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute;
	AuthLazyRoute: typeof AuthLazyRoute;
	UserLazyRoute: typeof UserLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	AuthLazyRoute: AuthLazyRoute,
	UserLazyRoute: UserLazyRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/user"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth": {
      "filePath": "auth.lazy.tsx"
    },
    "/user": {
      "filePath": "user.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
