name: Deploy to Docker Server (Test)

on:
    pull_request_review:
        types: [submitted]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-app_pr

jobs:
    build_and_push:
        name: Build Docker Container
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Get Metadata for Docker Image
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
            - name: Build & Push Docker Image
              id: push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./app/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
            
    pull_and_deploy:
        name: Pull and Deploy Docker Container
        runs-on: ubuntu-latest
        needs: build_and_push
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: SSH into Server
              uses: D3rHase/ssh-command-action@latest
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                    cd ${{ github.repository.name }}
                    git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
                    git checkout pr-${{ github.event.pull_request.number }}
                    docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
                    docker pull ${{ env.REGISTRY }}/${{github.actor}}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}
                    docker compose -f compose.external.yaml up --force-recreate -d
                    